Repository KUSITMS-30th-TEAM-A/backend, pull requests merged in 2024-10, with the labels that each got.

#6 [feat] : 커스텀 Exception을 변경한다.
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/java/kusitms/backend/global/code/BaseCode.java
  src/main/java/kusitms/backend/global/code/BaseErrorCode.java
  src/main/java/kusitms/backend/global/config/AppConfig.java
  src/main/java/kusitms/backend/global/config/CorsMvcConfig.java
  src/main/java/kusitms/backend/global/domain/BaseTimeEntity.java
  src/main/java/kusitms/backend/global/dto/ApiResponse.java
  src/main/java/kusitms/backend/global/exception/CustomException.java
  src/main/java/kusitms/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/kusitms/backend/global/status/ErrorStatus.java
  src/main/java/kusitms/backend/global/status/SuccessStatus.java
  src/main/java/kusitms/backend/test/exception/TestException.java
  src/main/java/kusitms/backend/test/presentation/TestController.java
  src/main/java/kusitms/backend/test/status/TestErrorStatus.java
  src/main/resources/application.yaml
Labels: 🚀 feat, ⚒️ chore, 😆 JUNHYEONG

#9 [feat] 소셜 로그인 및 추가정보 입력, 휴대폰 인증을 구현한다.
  src/main/java/kusitms/backend/auth/application/AuthService.java
  src/main/java/kusitms/backend/auth/dto/response/GoogleUserInfo.java
  src/main/java/kusitms/backend/auth/dto/response/KakaoUserInfo.java
  src/main/java/kusitms/backend/auth/dto/response/NaverUserInfo.java
  src/main/java/kusitms/backend/auth/dto/response/OAuth2UserInfo.java
  src/main/java/kusitms/backend/auth/handler/OAuth2LoginFailureHandler.java
  src/main/java/kusitms/backend/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/auth/jwt/JWTUtil.java
  src/main/java/kusitms/backend/auth/jwt/SecurityContextProvider.java
  src/main/java/kusitms/backend/auth/jwt/UserAuthentication.java
  src/main/java/kusitms/backend/auth/presentation/AuthController.java
  src/main/java/kusitms/backend/auth/status/AuthErrorStatus.java
  src/main/java/kusitms/backend/auth/status/AuthSuccessStatus.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/global/dto/ApiResponse.java
  src/main/java/kusitms/backend/global/redis/RedisManager.java
  src/main/java/kusitms/backend/global/util/CookieUtil.java
  src/main/java/kusitms/backend/test/presentation/TestController.java
  src/main/java/kusitms/backend/user/application/SmsService.java
  src/main/java/kusitms/backend/user/application/UserService.java
  src/main/java/kusitms/backend/user/domain/ProviderStatusType.java
  src/main/java/kusitms/backend/user/domain/User.java
  src/main/java/kusitms/backend/user/domain/repository/UserRepository.java
  src/main/java/kusitms/backend/user/dto/request/SendAuthCodeReq.java
  src/main/java/kusitms/backend/user/dto/request/SignUpReq.java
  src/main/java/kusitms/backend/user/dto/request/VerifyAuthCodeReq.java
  src/main/java/kusitms/backend/user/dto/response/UserInfoRes.java
  src/main/java/kusitms/backend/user/presentation/UserController.java
  src/main/java/kusitms/backend/user/status/UserErrorStatus.java
  src/main/java/kusitms/backend/user/status/UserSuccessStatus.java
Labels: 🚀 feat, 😆 JUNHYEONG

#18 [chore] : CICD 기능을 추가한다
  .github/workflows/cicd.yaml
  Dockerfile
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
Labels: 🚀 feat, ⚒️ chore, 🤯 SANGHO

#12 [feat] 유저로부터 키워드들을 입력받을 시 유저의 직관 성향과, 해당 구장의 구역을 최대3개 추천해준다.
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/stadium/application/StadiumService.java
  src/main/java/kusitms/backend/stadium/common/KeywordManager.java
  src/main/java/kusitms/backend/stadium/common/RecommendedTopRankedZones.java
  src/main/java/kusitms/backend/stadium/common/RecommendedUserProfile.java
  src/main/java/kusitms/backend/stadium/common/Reference.java
  src/main/java/kusitms/backend/stadium/common/ReferencesGroup.java
  src/main/java/kusitms/backend/stadium/domain/enums/JamsilStadiumStatusType.java
  src/main/java/kusitms/backend/stadium/domain/enums/KtWizStadiumStatusType.java
  src/main/java/kusitms/backend/stadium/domain/enums/ProfileStatusType.java
  src/main/java/kusitms/backend/stadium/domain/enums/StadiumStatusType.java
  src/main/java/kusitms/backend/stadium/dto/request/TopRankedZoneRequestDto.java
  src/main/java/kusitms/backend/stadium/dto/response/TopRankedZoneResponseDto.java
  src/main/java/kusitms/backend/stadium/presentation/StadiumController.java
  src/main/java/kusitms/backend/stadium/status/StadiumErrorStatus.java
  src/main/java/kusitms/backend/stadium/status/StadiumSuccessStatus.java
Labels: 🚀 feat, 😆 JUNHYEONG

#17 [feat] : 가이드 챗봇을 이용할 수 있다
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/chatbot/application/ChatbotService.java
  src/main/java/kusitms/backend/chatbot/domain/enums/BaseballGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/FacilityGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/GuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/MannerGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/ParkingGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/StadiumGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/dto/GetGuideChatbotAnswerResponse.java
  src/main/java/kusitms/backend/chatbot/presentation/ChatbotController.java
  src/main/java/kusitms/backend/chatbot/status/ChatbotErrorStatus.java
  src/main/java/kusitms/backend/chatbot/status/ChatbotSuccessStatus.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
Labels: 🚀 feat, 🤯 SANGHO

#14 [feat] Rest Docs와 Swagger를 연결하여 사용하여 문서화 작업을 실행한다.
  .gitignore
  build.gradle
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/global/config/CorsMvcConfig.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/test/application/TestService.java
  src/main/java/kusitms/backend/test/dto/request/TestDocsRequestDto.java
  src/main/java/kusitms/backend/test/dto/response/TestDocsResponseDto.java
  src/main/java/kusitms/backend/test/presentation/TestController.java
  src/main/resources/application.yaml
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/kusitms/backend/configuration/ControllerTestConfig.java
  src/test/java/kusitms/backend/test/TestControllerTest.java
Labels: 🚀 feat, ⚒️ chore, 😆 JUNHYEONG

#22 [feat] : 클로바 챗봇과 자유롭게 대화할 수 있다
  build.gradle
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/chatbot/application/ChatbotService.java
  src/main/java/kusitms/backend/chatbot/application/ClovaRequestFactory.java
  src/main/java/kusitms/backend/chatbot/application/ClovaService.java
  src/main/java/kusitms/backend/chatbot/application/MessageFactory.java
  src/main/java/kusitms/backend/chatbot/domain/enums/Role.java
  src/main/java/kusitms/backend/chatbot/dto/request/ClovaRequest.java
  src/main/java/kusitms/backend/chatbot/dto/request/GetClovaChatbotAnswerRequest.java
  src/main/java/kusitms/backend/chatbot/dto/request/Message.java
  src/main/java/kusitms/backend/chatbot/dto/response/ClovaChatbotAnswer.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetClovaChatbotAnswerResponse.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetGuideChatbotAnswerResponse.java
  src/main/java/kusitms/backend/chatbot/dto/response/Result.java
  src/main/java/kusitms/backend/chatbot/infrastructure/ClovaApiClient.java
  src/main/java/kusitms/backend/chatbot/presentation/ChatbotController.java
  src/main/java/kusitms/backend/chatbot/status/ChatbotSuccessStatus.java
  src/main/java/kusitms/backend/global/config/WebClientConfig.java
  src/main/java/kusitms/backend/user/domain/User.java
  src/main/resources/application.yaml
Labels: 🚀 feat, 🔄 refactor, ⚒️ chore, 🤯 SANGHO

#25 [feat] 구역가이드 조회 API를 구현한다.
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/result/domain/enums/JamsilStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/KtWizStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/StadiumStatusType.java
  src/main/java/kusitms/backend/result/presentation/ResultController.java
  src/main/java/kusitms/backend/stadium/application/StadiumService.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZoneGuideResponseDto.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZonesNameResponseDto.java
  src/main/java/kusitms/backend/stadium/presentation/StadiumController.java
  src/main/java/kusitms/backend/stadium/status/StadiumErrorStatus.java
  src/main/java/kusitms/backend/stadium/status/StadiumSuccessStatus.java
  src/main/resources/application.yaml
Labels: 🚀 feat, 😆 JUNHYEONG

#24 [feat] : 에러 처리를 추가하며, 메세지를 정제하여 전달한다
  build.gradle
  src/main/java/kusitms/backend/chatbot/presentation/ChatbotController.java
  src/main/java/kusitms/backend/global/dto/ApiResponse.java
  src/main/java/kusitms/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/kusitms/backend/global/status/ErrorStatus.java
Labels: 🚨 fix, 🚀 feat, 🤯 SANGHO

#29 [fix] : 타입을 변경하여 int 범위 문제를 해결한다
  src/main/java/kusitms/backend/chatbot/dto/response/Result.java
Labels: 🚨 fix, 🔄 refactor, 🤯 SANGHO

#32 [feat] : 챗봇 기능에 대한 테스트 코드를 작성한다
  src/main/java/kusitms/backend/global/config/CorsMvcConfig.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/global/config/SwaggerConfig.java
  src/main/resources/application.yaml
  src/main/resources/static/docs/open-api-3.0.1.json
  src/main/resources/static/docs/openapi3.json
  src/test/java/kusitms/backend/chatbot/ChatbotControllerTest.java
Labels: 🚀 feat, 🎫 rename, 🌱 style, 🤯 SANGHO
