Repository KUSITMS-30th-TEAM-A/backend, pull requests merged in 2024-11, with the labels that each got.

#34 [fix] : 배포 도메인에서는 rest docs가 적용되지 않는 문제를 해결한다
  .github/workflows/cicd.yaml
  Dockerfile
  build.gradle
  src/main/resources/application.yaml
Labels: 🚨 fix, 🚀 feat, ⚒️ chore, 🤯 SANGHO

#36 [feat] : 에러 처리를 추가한다
  src/main/java/kusitms/backend/global/exception/GlobalExceptionHandler.java
Labels: 🚀 feat, 🤯 SANGHO

#41 [style] : 주석을 수정하여 코드의 의도를 명확히 설명한다
  src/main/java/kusitms/backend/chatbot/presentation/ChatbotController.java
  src/main/java/kusitms/backend/chatbot/status/ChatbotErrorStatus.java
  src/main/java/kusitms/backend/user/status/UserErrorStatus.java
Labels: 🌱 style, 🤯 SANGHO

#42 [feat] 신규 회원 회원가입시 닉네임 중복체크 API 추가
  .gitignore
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/user/application/UserService.java
  src/main/java/kusitms/backend/user/domain/entity/User.java
  src/main/java/kusitms/backend/user/domain/repository/UserRepository.java
  src/main/java/kusitms/backend/user/dto/request/CheckNicknameRequestDto.java
  src/main/java/kusitms/backend/user/dto/request/SignUpRequestDto.java
  src/main/java/kusitms/backend/user/dto/response/UserInfoResponseDto.java
  src/main/java/kusitms/backend/user/presentation/UserController.java
  src/main/java/kusitms/backend/user/status/UserErrorStatus.java
  src/main/java/kusitms/backend/user/status/UserSuccessStatus.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: 🚀 feat, 😆 JUNHYEONG

#45 [feat] User, Auth 도메인의 테스트코드를 작성한다.
  dump.rdb
  src/main/java/kusitms/backend/auth/jwt/JWTUtil.java
  src/main/java/kusitms/backend/user/application/UserService.java
  src/main/java/kusitms/backend/user/presentation/UserController.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/kusitms/backend/auth/AuthControllerTest.java
  src/test/java/kusitms/backend/test/TestControllerTest.java
  src/test/java/kusitms/backend/user/UserControllerTest.java
Labels: 🚀 feat, 😆 JUNHYEONG

#49 [feat] : 구역 추천 결과 - 프로필 정보 조회 시 이미지를 함께 반환한다
  build.gradle
  src/main/java/kusitms/backend/global/config/S3Config.java
  src/main/java/kusitms/backend/result/application/ResultService.java
  src/main/java/kusitms/backend/result/domain/entity/Profile.java
  src/main/java/kusitms/backend/result/domain/enums/ProfileStatusType.java
  src/main/java/kusitms/backend/result/dto/response/GetProfileResponseDto.java
  src/main/resources/application.yaml
  src/test/java/kusitms/backend/result/ResultControllerTest.java
Labels: 🚀 feat, ⚒️ chore, 🤯 SANGHO

#53 [fix] : cors origin을 추가한다
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
Labels: 🚨 fix, 🤯 SANGHO

#54 [feat] 야구 문화 API 구현 및 테스트코드를 작성한다.
  build.gradle
  src/main/java/kusitms/backend/auth/jwt/JWTFilter.java
  src/main/java/kusitms/backend/culture/application/EntertainmentService.java
  src/main/java/kusitms/backend/culture/application/FoodService.java
  src/main/java/kusitms/backend/culture/domain/entity/Entertainment.java
  src/main/java/kusitms/backend/culture/domain/entity/Food.java
  src/main/java/kusitms/backend/culture/domain/enums/Boundary.java
  src/main/java/kusitms/backend/culture/domain/enums/Course.java
  src/main/java/kusitms/backend/culture/domain/repository/EntertainmentRepository.java
  src/main/java/kusitms/backend/culture/domain/repository/FoodRepository.java
  src/main/java/kusitms/backend/culture/domain/repository/custom/FoodRepositoryCustom.java
  src/main/java/kusitms/backend/culture/domain/repository/custom/FoodRepositoryImpl.java
  src/main/java/kusitms/backend/culture/dto/response/GetEntertainmentsResponseDto.java
  src/main/java/kusitms/backend/culture/dto/response/GetFoodsResponseDto.java
  src/main/java/kusitms/backend/culture/presentation/EntertainmentController.java
  src/main/java/kusitms/backend/culture/presentation/FoodController.java
  src/main/java/kusitms/backend/culture/status/EntertainmentSuccessStatus.java
  src/main/java/kusitms/backend/culture/status/FoodErrorStatus.java
  src/main/java/kusitms/backend/culture/status/FoodSuccessStatus.java
  src/main/java/kusitms/backend/global/config/QueryDslConfig.java
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/result/domain/entity/Profile.java
  src/main/java/kusitms/backend/result/dto/response/GetProfileResponseDto.java
  src/main/java/kusitms/backend/result/dto/response/GetZonesResponseDto.java
  src/main/java/kusitms/backend/result/dto/response/SaveTopRankedZoneResponseDto.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZonesNameResponseDto.java
  src/main/java/kusitms/backend/user/dto/response/UserInfoResponseDto.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/kusitms/backend/culture/EntertainmentControllerTest.java
  src/test/java/kusitms/backend/culture/FoodControllerTest.java
Labels: 🚀 feat, 😆 JUNHYEONG

#55 [feat] : 특정 가이드 챗봇 답변에 이미지 URL을 함께 반환한다
  src/main/java/kusitms/backend/chatbot/domain/enums/ParkingGuideAnswer.java
Labels: 🚀 feat, 🤯 SANGHO

#56 [feat] : 구역 가이드 정보 조회 시 이미지 URL을 함께 반환한다
  src/main/java/kusitms/backend/result/domain/enums/JamsilStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/KtWizStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/StadiumStatusType.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZoneGuideResponseDto.java
  src/test/java/kusitms/backend/stadium/StadiumControllerTest.java
Labels: 🚀 feat, 🤯 SANGHO

#62 [remove] : 불필요한 도메인 및 테스트 코드를 제거한다
  src/main/java/kusitms/backend/test/application/TestService.java
  src/main/java/kusitms/backend/test/dto/request/TestDocsRequestDto.java
  src/main/java/kusitms/backend/test/dto/response/TestDocsResponseDto.java
  src/main/java/kusitms/backend/test/presentation/TestController.java
  src/main/java/kusitms/backend/test/status/TestErrorStatus.java
  src/main/java/kusitms/backend/test/status/TestSuccessStatus.java
  src/test/java/kusitms/backend/test/TestControllerTest.java
Labels: ✂️ remove, 🤯 SANGHO

#60 [feat] : 테스트 코드를 수정하여 REST Docs에 설명을 추가한다
  src/test/java/kusitms/backend/chatbot/ChatbotControllerTest.java
  src/test/java/kusitms/backend/culture/EntertainmentControllerTest.java
  src/test/java/kusitms/backend/culture/FoodControllerTest.java
  src/test/java/kusitms/backend/result/ResultControllerTest.java
  src/test/java/kusitms/backend/stadium/StadiumControllerTest.java
  src/test/java/kusitms/backend/user/UserControllerTest.java
Labels: 🚀 feat, 🤯 SANGHO

#64 [feat] 구역 정보 조회에서 색상 정보를 추가한다.
  dump.rdb
  src/main/java/kusitms/backend/result/application/ResultService.java
  src/main/java/kusitms/backend/result/domain/entity/Zone.java
  src/main/java/kusitms/backend/result/domain/enums/JamsilStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/KtWizStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/StadiumStatusType.java
  src/main/java/kusitms/backend/result/dto/response/GetZonesResponseDto.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZoneGuideResponseDto.java
  src/main/java/kusitms/backend/stadium/presentation/StadiumController.java
  src/test/java/kusitms/backend/result/ResultControllerTest.java
  src/test/java/kusitms/backend/stadium/StadiumControllerTest.java
Labels: 🚀 feat, 😆 JUNHYEONG

#66 [refactor] : 구장명 및 확장자명을 일부 변경한다
  src/main/java/kusitms/backend/result/application/ResultService.java
  src/main/java/kusitms/backend/result/domain/enums/ProfileStatusType.java
  src/main/java/kusitms/backend/stadium/application/StadiumService.java
  src/test/java/kusitms/backend/result/ResultControllerTest.java
  src/test/java/kusitms/backend/stadium/StadiumControllerTest.java
Labels: 🚨 fix, 🔄 refactor, 🤯 SANGHO

#69 [feat] : 이미지 URL & 소개 문구 & 색상 필드를 추가한다
  src/main/java/kusitms/backend/result/application/ResultService.java
  src/main/java/kusitms/backend/result/common/Reference.java
  src/main/java/kusitms/backend/result/domain/entity/Profile.java
  src/main/java/kusitms/backend/result/domain/enums/JamsilStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/KtWizStadiumStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/ProfileStatusType.java
  src/main/java/kusitms/backend/result/domain/enums/StadiumStatusType.java
  src/main/java/kusitms/backend/result/dto/response/GetProfileResponseDto.java
  src/main/java/kusitms/backend/stadium/application/StadiumService.java
  src/main/java/kusitms/backend/stadium/domain/enums/StadiumInfo.java
  src/main/java/kusitms/backend/stadium/dto/response/GetStadiumInfosResponseDto.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZoneGuideResponseDto.java
  src/main/java/kusitms/backend/stadium/dto/response/GetZonesNameResponseDto.java
  src/main/java/kusitms/backend/stadium/presentation/StadiumController.java
  src/main/java/kusitms/backend/stadium/status/StadiumSuccessStatus.java
  src/test/java/kusitms/backend/result/ResultControllerTest.java
  src/test/java/kusitms/backend/stadium/StadiumControllerTest.java
Labels: 🚨 fix, 🚀 feat, 🤯 SANGHO

#71 [feat] : 배포 도메인 및 임시 도메인 cors를 허용한다
  src/main/java/kusitms/backend/global/config/SecurityConfig.java
  src/main/java/kusitms/backend/stadium/application/StadiumService.java
  src/main/java/kusitms/backend/stadium/domain/enums/StadiumInfo.java
  src/main/java/kusitms/backend/stadium/dto/response/GetStadiumInfosResponseDto.java
  src/main/java/kusitms/backend/stadium/presentation/StadiumController.java
  src/test/java/kusitms/backend/stadium/StadiumControllerTest.java
Labels: 🚨 fix, 🚀 feat, 🤯 SANGHO

#75 [feat] 잠실종합운동장의 익사이팅석 색상을 변경한다.
  src/main/java/kusitms/backend/result/domain/enums/JamsilStadiumStatusType.java
Labels: 🚀 feat, 😆 JUNHYEONG

#79 [refactor] : Auth, User, Jwt 관련 코드 리팩토링을 진행한다
  src/main/java/kusitms/backend/auth/application/AuthService.java
  src/main/java/kusitms/backend/auth/dto/response/TokenResponseDto.java
  src/main/java/kusitms/backend/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/kusitms/backend/auth/jwt/JWTUtil.java
  src/main/java/kusitms/backend/auth/jwt/JwtProperties.java
  src/main/java/kusitms/backend/auth/presentation/AuthController.java
  src/main/java/kusitms/backend/auth/status/AuthErrorStatus.java
  src/main/java/kusitms/backend/global/redis/RedisManager.java
  src/main/java/kusitms/backend/global/status/ErrorStatus.java
  src/main/java/kusitms/backend/global/util/CookieUtil.java
  src/main/java/kusitms/backend/user/application/UserService.java
  src/main/resources/application.yaml
  src/test/java/kusitms/backend/auth/AuthControllerTest.java
Labels: 🚀 feat, 🔄 refactor, 🤯 SANGHO

#81 [feat] 키워드에 따른 구역 추천 결과를 3개 반환하도록 수정한다.
  src/main/java/kusitms/backend/result/common/RecommendTopRankedZones.java
  src/main/java/kusitms/backend/result/domain/entity/Result.java
  src/main/java/kusitms/backend/result/domain/enums/KtWizStadiumStatusType.java
Labels: 🚀 feat, 😆 JUNHYEONG

#89 [fix] : 스타디움 구역 정보 중복 & 구역 추천(KT) 문제를 해결한다
  src/main/java/kusitms/backend/result/domain/enums/KtWizStadiumStatusType.java
  src/main/java/kusitms/backend/stadium/application/StadiumService.java
Labels: 🚨 fix, 🚀 feat, 🤯 SANGHO

#87 [refactor] : global에서의 의존성을 제거하고, 닉네임 중복 확인 시 분산 락을 활용한다
  src/main/java/kusitms/backend/auth/status/AuthErrorStatus.java
  src/main/java/kusitms/backend/global/redis/DistributedLockManager.java
  src/main/java/kusitms/backend/global/redis/RedisManager.java
  src/main/java/kusitms/backend/global/status/ErrorStatus.java
  src/main/java/kusitms/backend/global/util/CookieUtil.java
  src/main/java/kusitms/backend/user/application/UserService.java
Labels: 🚀 feat, 🔄 refactor, 🤯 SANGHO

#85 [refactor] : Chatbot 관련 리팩토링을 진행한다
  src/main/java/kusitms/backend/chatbot/application/ChatbotService.java
  src/main/java/kusitms/backend/chatbot/application/ClovaRequestFactory.java
  src/main/java/kusitms/backend/chatbot/application/ClovaService.java
  src/main/java/kusitms/backend/chatbot/application/MessageFactory.java
  src/main/java/kusitms/backend/chatbot/domain/enums/Role.java
  src/main/java/kusitms/backend/chatbot/dto/request/ChatbotRequestDto.java
  src/main/java/kusitms/backend/chatbot/dto/request/ClovaRequest.java
  src/main/java/kusitms/backend/chatbot/dto/request/ClovaRequestDto.java
  src/main/java/kusitms/backend/chatbot/dto/request/GetClovaChatbotAnswerRequestDto.java
  src/main/java/kusitms/backend/chatbot/dto/request/Message.java
  src/main/java/kusitms/backend/chatbot/dto/request/MessageDto.java
  src/main/java/kusitms/backend/chatbot/dto/response/ClovaChatbotAnswer.java
  src/main/java/kusitms/backend/chatbot/dto/response/ClovaChatbotAnswerDto.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetClovaChatbotAnswerResponse.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetClovaChatbotAnswerResponseDto.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetGuideChatbotAnswerResponse.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetGuideChatbotAnswerResponseDto.java
  src/main/java/kusitms/backend/chatbot/dto/response/ResultDto.java
  src/main/java/kusitms/backend/chatbot/infrastructure/ChatbotApiClient.java
  src/main/java/kusitms/backend/chatbot/infrastructure/ClovaApiClient.java
  src/main/java/kusitms/backend/chatbot/presentation/ChatbotController.java
  src/main/java/kusitms/backend/chatbot/status/ChatbotErrorStatus.java
  src/main/java/kusitms/backend/global/dto/ApiResponse.java
  src/main/java/kusitms/backend/global/exception/GlobalExceptionHandler.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/kusitms/backend/chatbot/ChatbotControllerTest.java
Labels: 🚀 feat, 🔄 refactor, 🤯 SANGHO

#93 [refactor] : Chatbot 도메인을 DDD 구조로 리팩토링한다
  build.gradle
  src/main/java/kusitms/backend/chatbot/application/ClovaService.java
  src/main/java/kusitms/backend/chatbot/application/dto/request/ChatbotRequestDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/request/ClovaRequestDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/request/GetClovaChatbotAnswerRequestDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/request/MessageDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/response/ClovaChatbotAnswerDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/response/GetClovaChatbotAnswerResponseDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/response/GetGuideChatbotAnswerResponseDto.java
  src/main/java/kusitms/backend/chatbot/application/dto/response/ResultDto.java
  src/main/java/kusitms/backend/chatbot/application/factory/ClovaRequestFactory.java
  src/main/java/kusitms/backend/chatbot/application/factory/MessageFactory.java
  src/main/java/kusitms/backend/chatbot/application/service/ChatbotApplicationService.java
  src/main/java/kusitms/backend/chatbot/domain/service/ChatbotApiClient.java
  src/main/java/kusitms/backend/chatbot/infra/adapter/ClovaApiClient.java
  src/main/java/kusitms/backend/chatbot/infra/config/WebClientConfig.java
  src/main/java/kusitms/backend/chatbot/presentation/ChatbotController.java
  src/test/java/kusitms/backend/chatbot/ChatbotControllerTest.java
Labels: 🚀 feat, 🔄 refactor, ✂️ remove, ⚒️ chore, 🤯 SANGHO

#94 [feat] : 챗봇 서비스 단위 테스트 코드를 작성한다
  build.gradle
  src/test/java/kusitms/backend/chatbot/application/factory/ClovaRequestFactoryTest.java
  src/test/java/kusitms/backend/chatbot/application/factory/MessageFactoryTest.java
  src/test/java/kusitms/backend/chatbot/application/service/ChatbotApplicationServiceTest.java
  src/test/java/kusitms/backend/chatbot/infra/adapter/ClovaApiClientTest.java
  src/test/java/kusitms/backend/chatbot/presentation/ChatbotControllerTest.java
Labels: 🚀 feat, 🔄 refactor, 🤯 SANGHO

#96 [feat] : 유저 서비스 단위 테스트 코드를 작성한다
  src/test/java/kusitms/backend/user/application/service/UserApplicationServiceTest.java
  src/test/java/kusitms/backend/user/presentation/UserEntityControllerTest.java
Labels: 🚀 feat, 🔄 refactor, 🤯 SANGHO

#95 [feat] : 스타디움 서비스 단위 테스트 코드를 작성한다
  src/test/java/kusitms/backend/stadium/application/service/EntertainmentApplicationServiceTest.java
  src/test/java/kusitms/backend/stadium/application/service/FoodApplicationServiceTest.java
  src/test/java/kusitms/backend/stadium/application/service/StadiumApplicationServiceTest.java
  src/test/java/kusitms/backend/stadium/domain/service/StadiumDomainServiceTest.java
  src/test/java/kusitms/backend/stadium/presentation/EntertainmentControllerTest.java
  src/test/java/kusitms/backend/stadium/presentation/FoodControllerTest.java
  src/test/java/kusitms/backend/stadium/presentation/StadiumControllerTest.java
Labels: 🚀 feat, 🔄 refactor, 🤯 SANGHO

#83 [feat] : 챗봇 관련 데이터를 수정한다
  src/main/java/kusitms/backend/chatbot/application/ChatbotService.java
  src/main/java/kusitms/backend/chatbot/domain/enums/BaseballGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/FacilityGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/GuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/MannerGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/ParkingGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/StadiumGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/dto/response/GetGuideChatbotAnswerResponse.java
  src/test/java/kusitms/backend/chatbot/ChatbotControllerTest.java
Labels: 🚀 feat, 🤯 SANGHO

#98 [feat] : 1차 리팩토링 코드를 기반으로 배포를 진행한다
  .github/workflows/cicd.yaml
  .gitignore
  README.md
  src/main/java/kusitms/backend/chatbot/application/dto/response/GetGuideChatbotAnswerResponseDto.java
  src/main/java/kusitms/backend/chatbot/application/service/ChatbotApplicationService.java
  src/main/java/kusitms/backend/chatbot/domain/enums/BaseballGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/FacilityGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/GuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/MannerGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/ParkingGuideAnswer.java
  src/main/java/kusitms/backend/chatbot/domain/enums/StadiumGuideAnswer.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/kusitms/backend/chatbot/presentation/ChatbotControllerTest.java
  src/test/java/kusitms/backend/result/presentation/ResultControllerTest.java
Labels: 🚀 feat, 🔄 refactor, ⚒️ chore, 🤯 SANGHO

#99 [docs] : 리드미를 수정한다
  README.md
Labels: 📄 docs, 🤯 SANGHO

#101 [feat] 즐길거리, 먹거리에 대한 스타디움명 문서를 수정한다.
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/kusitms/backend/stadium/presentation/EntertainmentControllerTest.java
  src/test/java/kusitms/backend/stadium/presentation/FoodControllerTest.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/global/domain/QBaseTimeEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/result/infra/jpa/entity/QProfileEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/result/infra/jpa/entity/QResultEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/result/infra/jpa/entity/QZoneEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/stadium/infra/jpa/entity/QEntertainmentEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/stadium/infra/jpa/entity/QFoodEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/stadium/infra/jpa/entity/QStadiumEntity.java
  task ':build'/generated/sources/annotationProcessor/java/main/kusitms/backend/user/infra/jpa/entity/QUserEntity.java
Labels: 🚀 feat, 😆 JUNHYEONG
